### ISSUE TITLE
Lost synchro audio-video

### ISSUE THREAD

**Issue by veka-server** [brianwernick/ExoMedia#109]
Hello,

When I try to play an hls video (twitch), it freezes at launch for a second but not the sound.

This will create a desynchronization between video and audio.

can you help me ?

**Comment by brianwernick** [comment]
Would you provide an example url

**Comment by veka-server** [comment]
sure,
Test 1 :
http://vod.ak.hls.ttvnw.net/v1/AUTH_system/vods_8240/fantabobshow_19554040496_400314265/chunked/index-muted-90W28YU1VN.m3u8

Test 2 :
 http://vod.ak.hls.ttvnw.net/v1/AUTH_system/vods_600a/rpglimitbreak_19592162624_401381317/chunked/index-muted-AENJHXMNFM.m3u8

**Comment by brianwernick** [comment]
Hmm, I'm not having the audio continue when the video doesn't on my Nexus 6P.  What device and OS level are you seeing this on?  Are you actually seeing the audio become out-of-sync with the video, or is the video just dropping frames?

**Comment by veka-server** [comment]
Android 4.4.2
Phone: Polaroid pro 4544P

When I play the video the first 3 seconds are correct.
Then, the video freezes/pause for a second and restart at the same location without a lost sequence.

the audio does not freeze when the video freeze.

**Comment by brianwernick** [comment]
Hmm, It might be an issue on 4.4.2 then, though this might be an issue in the backing ExoPlayer library.  I'll look in to it when I get some time later this week.

**Comment by brianwernick** [comment]
Hmm, I can't seem to duplicate the issue with any of my devices (4.1 - 6.0).  After researching a little more, it looks like the ExoPlayer has problems on certain devices due to them reporting playback positions incorrectly or sometimes for unknown reasons (there are currently a few bugs open about playback speed/sync issues).  

This issue is most likely one that needs to be logged against the ExoPlayer (or chimed in on an existing bug)
