### ISSUE TITLE
player bugs

### ISSUE THREAD

**Issue by ehaahe** [brianwernick/ExoMedia#116]
1. when the video is in the completion status,the play function is not available
2. when i change the video to fullscreen,can i change the control panel of the video?

**Comment by brianwernick** [comment]
1) This is working as designed.  If you want to replay the video you will have to seek to the start in order to play again.

2) Currently there is no supported way to modify the DefaultControls.  This is a change that has been made in the 3.0 branch though, so once that is release you can either modify the default controls provided, or create your own.
