### ISSUE TITLE
setZOrderOnTop(true) cannot resolve.

### ISSUE THREAD

**Issue by Okiturk** [brianwernick/ExoMedia#139]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.5`
 - Device OS version: `4.0.4`
 - Devide Manufacturer: `Samsung`
 - Device Name: `P7500`
 
setZOrderOnTop(true) can not resolve. How to set z-order of  EMVideoView?

**Comment by brianwernick** [comment]
The method `setZOrderOnTop()` is only provided by the `SurfaceView` that the Android VideoView uses.  Because the EMVideoView only uses the Android VideoView on devices below API 16 or non CTS compliant devices it isn't supported.  If you need to set the Z-Order then place the EMVideoView lower in the xml layout file.

Because the next version (3.0) will not be using a `SurfaceView`, ExoMedia will not add that functionality.

**Comment by Okiturk** [comment]
Placing the EMVideoView lover in the xml layout way didn't work on devices below API 16. Map fragment always stay over the EMVideoView. But I found a solution. I add simple line in initView method at EMVideoView.java   

`if(Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN) videoView.setZOrderMediaOverlay(true);`

That worked for me.

Thank you.
