### ISSUE TITLE
Can I override the default controller???

### ISSUE THREAD

**Issue by sujitkjha** [brianwernick/ExoMedia#147]
I want to over ride the default controller with new icon as well as I want to add some more functionality, like repeat the song and navigate to the playlist by clicking the icon on controller. 

I'm new in android and doing a project for my company using exomedia player. I'm using audio player  feature of Exomedia player as it is done in demo. I will rather say I'm using the demo exomedia player as my starting point of my project.

**Comment by se-bastiaan** [comment]
Are you referring to the MediaSession controller? In that case you can get the EMLockScreen and change almost everything you want.

**Comment by sujitkjha** [comment]
No, I am using Demo app and tried to change the controller all the way but didn't succeeded. Can you please guide me how to do it @se-bastiaan

**Comment by se-bastiaan** [comment]
To what controller are you referring exactly?

**Comment by sujitkjha** [comment]
Default controller provided in demo app

**Comment by brianwernick** [comment]
Currently (in 2.5.x) there is no way to override or specify your own `DefaultControls` (other than overriding quite a few fields and objects in the `EMVideoView`.  This has been re-architected in the `3.0` (dev) branch to allow specifying your own VideoControls (renamed from DefaultControls).

If you don't need to release for a while (1 - 2 months) then you can probably use a local copy of the 3.0 (by running `./gradlew clean build aRel uploadArchives`) otherwise you will need to wait.

**Comment by sujitkjha** [comment]
Thanks for your support @brianwernick. I started using the 3.0 demo app as my start point and only problem I'm facing is how to override the default controller. I am working on an Music app that offer free and paid music. User can save the audio as well. your help will be greatly appreciated.

**Comment by brianwernick** [comment]
There is the [setControls()](https://github.com/brianwernick/ExoMedia/blob/3.0/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java#L324) method in the `EMVideoView` that you need to call in order to specify the controls.  This will take place of the `useDefaultControls` layout attribute (and the historical `setDefaultControlsEnabled()`

For the best understanding you should look at the source for the [VideoControls](https://github.com/brianwernick/ExoMedia/blob/3.0/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java) which is separated in to the base class `VideoControls` and the two format controls `VideoControlsMobile` and `VideoControlsLeanback`.  You will need to override and specify each of these independently

**Comment by sujitkjha** [comment]
I'm using demo app, Please guide me how to do it?? I'm sorry but I'm very new to android
