### ISSUE TITLE
Shutter Calculation Wrong

### ISSUE THREAD

**Issue by eygraber** [brianwernick/ExoMedia#171]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `5.1.1`
 - Devide Manufacturer: `Motorola`
 - Device Name: `Droid Turbo`
 
###### Reproduction Steps
 1.  Play demo 3GP
 2.  Rotate device to landscape
 3.  Rotate device to portrait

###### Expected Result
 1.  When rotating the shutters should fill the rest of the screen

###### Actual Result
 1. The shutters do not fill the rest of the screen (their size is 0)

**Comment by brianwernick** [comment]
Now that I looked in to the video shutters again, I don't need them anymore because you can now set the background to the EMVideoView and have the ResizingTextureView correctly abide by it (unlike the old SurfaceView implementations).  I'll do a little more testing, but I should be able to completely remove them
