### ISSUE TITLE
How to handle next, previous and push button in notification and update accordingly 

### ISSUE THREAD

**Issue by sujitkjha** [brianwernick/ExoMedia#179]
Hello Everybody out here,
I'm using Exomedia Demo app as my starting point for my music app project. In my app music can be played online as well as offline. In my music player app when data is offline I extract all the meta data and manually set it wherever required but setting bitmap image is hard-part for me thou I have made all the changes, when I'm in AudioPlayerActivity and click next artwork get changed at both place in notification as well in player screen but when I go to notification screen and click next notification screen artwork and other place it wont get changed. Please help !!!

**Comment by brianwernick** [comment]
Why are you manually extracting metadata from a downloaded media item?
  You just need to pass in the local URI for the media to be correctly parsed

**Comment by brianwernick** [comment]
Also, you should look at migrating to [PlaylistCore](https://github.com/brianwernick/PlaylistCore) for your playlist support as it has been deprecated and will be removed in `3.0.0`

**Comment by sujitkjha** [comment]
Can you please explain in reference to Demo where I need to pass local uri to get things done automatically????? Without extracting metadata ????

**Comment by brianwernick** [comment]
Sorry, I was wrong.  I was thinking of a job that I did recently; the only metadata that is extracted is playback information such as duration, audio channels, etc.  What I'm assuming you are doing is extracting the title, album, artist, etc. which isn't automatically done :(...

As far as the image in the removeViews (lockscreen, etc.) and notification are concerned; as long as the `PlaylistItem` (`IPlaylistItem` in `PlaylistCore`) returns a different image URL then they should get updated.  If you are returning null, or an otherwise non-unique URL then you will need to monitor the playlist item change event and retrieve the new image manually, calling `onLargeNotificationImageUpdated` and `onLockScreenArtworkUpdated` in the playlistService.
