### ISSUE TITLE
How to make use of performShuffle() of EMPlaylistService?

### ISSUE THREAD

**Issue by vsay01** [brianwernick/ExoMedia#184]
- [YES ] I have verified there are no duplicate active or recent bugs, questions, or requests

I use ExoMedia 2.5.6

I want to allow user to shuffle the musics; in other words, allow user to randomly play the music in the playlist.

I am confuse with the description in the document given as following.
`performShuffle() Performs the functionality to repeat the current media item in playback.`

Is this refers to repeat one media item and not shuffle the media item in the list?

**I think I am going to random a value ranged between the playlist size and play that media of the random value, but 
where should I write this ? 
Is it performShuffle() or performMediaCompletion()? or onPlaylistItemChanged()?
What is the purpose of the performShuffle()**

**Comment by brianwernick** [comment]
Yeah, The "repeat" looks like a typo in the documentation, I'll fix that in the documentation for [PlaylistCore](https://github.com/brianwernick/PlaylistCore) which is the new home for the playlist functionality (in the 3.0.0 release)

The `invokeShuffle()` method in the `EMPlaylistManager` just sends the command to the `EMPlaylistService`. In order to provide shuffle functionality you will need to override `performShuffle()` in the `EMPlaylistService` on your own to provide the expected functionality.  This was meant as a convenience path to simplify a more common functionality that should be specific to the app.

When implementing the `performShuffle()` you will need to 
 * Update the EMPlaylistManager item ordering
 * Make sure the current media in playback is still the current item selected (first) in the playlist

**Comment by vsay01** [comment]
@brianwernick Sure i'll try that out.

**Comment by vsay01** [comment]
@brianwernick I have hard time to implement where we need to change the order. So basically I allow user to click on the shuffle in the AudioPlayerActivity so it means that the current audio is playing already and the random will start from next play.

What I am trying to do is that in the perfromShuffle() function:
- random the value range from 0 to size of play list
- assign that random value to next play 

In AudioService

```
@Override
    protected void performShuffle() {
        super.performShuffle();
        AudioPlayerActivity.arr_int.add(getMediaPlaylistManager().getCurrentIndex());
        int nextRandomIndex = Utils.generateRandom(0, getMediaPlaylistManager().getPlayListSize(), AudioPlayerActivity.arr_int);
        //TODO Set nextRandomIndex for nextPlay
    }
```

Is it the right approach? When you mentioned update the EMPlaylistManager item ordering, I think it might be different approach..

**Comment by brianwernick** [comment]
This is a more generic question now that should be asked on StackOverflow or a similar website as it is dealing with randomizing a list of items.

**Comment by vsay01** [comment]
@brianwernick  maybe my question confuse you.

What I mean is that where and how i set the next play id for the current playlist? since the way i shuffle here i didn't randomise the order of the list EMPlaylistManager. That is why I asked if that is the right approach.

In the previous response, you mentioned Update the EMPlaylistManager item ordering. If I go with this approach, since the performShuffle() is in AudioService class how can i get the reference of current playlist ?
Thank
