### ISSUE TITLE
[Q] How you think about having multiple ExoPlayer instance at once?

### ISSUE THREAD

**Issue by eneim** [brianwernick/ExoMedia#214]
This is not an issue report, I would like to ask for some practice on ExoPlayer which I believe you are doing well:

- I'm creating something which could support auto video playback for list (a RecyclerView). It means that you can have something like Facebook's feed.

But doing so, I will have more than one MediaPlayer instances at once. I read some related issues on ExoPlayer repo, it turns out that it's possible to have multiple ExoPlayer instance at once, as long as the hardware support (the number of decoder instance, for example). But I'm wondering if having multiple Player instance at once is a bad practice or not. I experienced how Youtube Player API works, it create and preserve at most one Player instance. So I really want to know how you think about having multiple Player instance and what should be the way to support multiple Playback widget. Thanks.

**Comment by brianwernick** [comment]
Ideally you would just show a preview image in a list, then when the user clicks on it (to play) you would either launch a new fragment or replace the `ImageView` with a video view.  And while there is no specified limit (that I know of) for how many instances of the ExoPlayer you can have simultaneously, I've only personally dealt with 4-5 (in a view pager) and that didn't have any problems.

On a related note; auto playing videos (like FB does) as the user scrolls is a pretty bad practice because it removes the ability for the user to limit their network usage (and the increased battery use for network/cpu usage).

**Comment by eneim** [comment]
Hm I don't think applying new UX is considered a bad practice **BECAUSE** it consumes more system resource. IMO, to retrieve that kind of UX, more system resource consumption is a trade off. And that's why devices involve with more powerful equipments. Finally it depends on the developer's choice. And of course the developer should always provide the option to turn off those UX though.

Personally I would try to narrow down as much as possible the resource required for that, so I'll try to figure our the way to use a global instance of ExoPlayer.
