### ISSUE TITLE
onSeekCompletionListener

### ISSUE THREAD

**Issue by Troachaps** [brianwernick/ExoMedia#217]
Is there any way to implement onSeekCompleted listener,
In my old project I was using VideoVIew and in it,s onPrepared event I use media player object to set  onSeekCompleted event,But in exo-player onPrepared event MediaPlayer parameter is always null.
I tested and verified this issue on 2 devices(Prekitkat and kitkat)

**Comment by brianwernick** [comment]
The listeners have been completely swapped out in `3.0` to avoid confusion like this.  The reason `MediaPlayer` is null is because the ExoPlayer is being used and therefor we have no `MediaPlayer` to return.  Additionally, in 2.x and below there are no `onSeekCompletion` listeners integrated for the ExoPlayer implementations.

My recommendation would be to use the 3.0.0-preview3
