### ISSUE TITLE
video ad + content video

### ISSUE THREAD

**Issue by billyjoker** [brianwernick/ExoMedia#219]
Hi Brian, i've an issue i'd like you to say to me the best way to perform my scenario: in some cases i'd like to add an ad (or some ads) before loading the content video. After the reproduction of the ads, start the video. It would be as simple as replace the Uri or maybe adding ads + video into a playlist? What if this perform of insertion of an ad i execute at the middle of a video playback?

Thanks again!! #

**Comment by brianwernick** [comment]
Is this with 3.0? 2.5?

**Comment by billyjoker** [comment]
Is 2.5.6

**Comment by brianwernick** [comment]
If you are using the playlist you will need to add your own modifications to the service (so that the user can't skip the adds, etc.).  Other than that, I would just use the playlist mechanism; removing the adds from the history after they have been played (only if you support the previous functionality).

As far as playing an add mid-video is concerned, you will have to do your own custom logic for that, in those cases I wouldn't add it to the playlist, just have the video playback activity perform the logic itself.  Of course if you are going to add chromecast (or other similar functionality) then the custom logic will probably need to be handled in the playlist service (e.g. watch the current position for specific indexes, pause the current video, and play an add)

**Comment by billyjoker** [comment]
Thanks Brian, i'll work that way. The hard work will including mid ads as you said. Preroll ad (before the playback) seems to be easy using the playlist manager.

**Comment by ohenepee** [comment]
@brianwernick Will the playlist method offer a seamless playback (or video source switching, without screen blanking for a few seconds) or is there another method by which multiple videos can be combined as a single source to offer seamless playback?
