### ISSUE TITLE
EMVideoView cannot wrap content height

### ISSUE THREAD

**Issue by denis-trailin-hs** [brianwernick/ExoMedia#222]
- [ ✓] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0-preview3`
 - Device OS version: `N`
 - Devide Manufacturer: `HTC`
 - Device Name: `Nexus 9`
 
###### Reproduction Steps
 1..  Make a EMVideoView with layout params
```
android:layout_width="match_parent"
android:layout_height="wrap_content"
``` 
and a ScaleType of `FIT_CENTER`
2. Open any video
###### Expected Result
View height matches video height

###### Actual Result

View height expands to it's maximum size breaking any ScrollView that it's in. 
[screenshot](http://i.imgur.com/XDqYqjg.jpg)

**Comment by brianwernick** [comment]
As a note, you probably want `ScaleType.CENTER` instead of `ScaleType.FIT_CENTER`, not that it currently works with either

**Comment by billyjoker** [comment]
Include the following:

ExoMedia version: 2.5.6
Device OS version: L
Devide Manufacturer: Motorola
Device Name: Moto X 2014

I did as you said, steps i follow:

1. emVideoView.setScaleType(ScaleType.CENTER);
2. Open any video
3. Play the video well scaled (portrait)
4. Press home screen button (video is backgrounded now)
5. Return to the video view
6. Video is expended to full height
7. Automatically try to get well scaled...but don't, it scales with new dimensions, like zoomed
8. Repeat from step 4 produce same results

**Comment by brianwernick** [comment]
I've been thinking about this for the last few weeks and have decided that I'm not going to support `wrap_content` for a few reasons:
 1. When no video is loaded what is the size of the view? (0, 0) [NOTE: this is what the Android `VideoView` does]?
 2. If you have a preview image specified what is the size of the view? 
  1.  Does is match the image, then match the video when it is ready/playing?  What if they are different sizes?
 3. If you have the `VideoControls` enabled what is the minimum size they can be while still functioning?
   1. How would this be determined with the video and image sizes?
 4. By default the scale type is `FIT_CENTER` would we need to make that `CENTER` if `wrap_content` is specified on either width or height?
 5. What is the expected outcome when videos are different sizes (played in the same view)?
 6. How would the `wrap_content` look on an `xxxhdpi` device vs an `mdpi` device (because videos are just pixel values this makes a HUGE difference)

There are a few other minor ones but they could be worked out fairly easily so I'm not going to mention them.  Additionally, this list is shorter than is for the `1.x` and `2.x` versions due to major architectural changes that simplified calculations (such as not having the shutters anymore).

That being said, if you (or anyone in general) really wants to go through, figure out these cases, and implement the solution without breaking the current expected functionality then --by all means-- please create a PR

**Comment by brianwernick** [comment]
I forgot to mention, If you want a specific ratio you can use the `PercentRelativeLayout` in the support libraries or wrap it in a custom `ViewGroup` that contains the size to what you want

**Comment by denis-trailin-hs** [comment]
@brianwernick So what I've been doing is 
```
 mEMVideoView.setOnPreparedListener(() -> {
            FrameLayout.LayoutParams params = (FrameLayout.LayoutParams) mEMVideoView.getLayoutParams();
            params.height = (int) (mEMVideoView.getWidth() * VIDEO_ASPECT_RATION_NINE_SIXTEEN);
            mEMVideoView.setLayoutParams(params);
        });
```
Which overall has been pretty glitchy. The size for my videos sometimes seems to jump for no reason mid-video. I'll try `PercentRelativeLayout` and see how that works out but it would be nice to have some built in functionality for automatic height scaling. It would be very useful to be able to set the layout params to be the same as the video aspect ratio. Would that be a viable solution? 

This seems like pretty significant departure from in terms of emulating `VideoView`.
