### ISSUE TITLE
No default background color in 3.0.0

### ISSUE THREAD

**Issue by DrewCarlson** [brianwernick/ExoMedia#248]
Some time ago @hzsweers made the video background black by default, this seems to be missing from 3.0.0, was this an intentional removal?

**Comment by brianwernick** [comment]
This was on purpose.  The black background was a workaround another issue which is no longer present

**Comment by DrewCarlson** [comment]
OK. Does it not make sense leave it black for design reasons as it's common practice across numerous platforms to have a black video stage?

**Comment by brianwernick** [comment]
Because I wanted it to act as any other view you can specify the background color of your choosing with `android:background="@android:color/black"`, but by default it is transparent.  
Typically when in a fullscreen activity the activities/fragments background will already be black, in lists it will usually be the color of the items, etc.

**Comment by DrewCarlson** [comment]
> Because I wanted it to act as any other view

Fair enough, thanks anyway.

**Comment by brianwernick** [comment]
You're welcome.  As usual, if there are enough asking for this then it may change back to black :)
