### ISSUE TITLE
Rewind and Fast forward buttons are not visible on the controller

### ISSUE THREAD

**Issue by devanshuk** [brianwernick/ExoMedia#271]
- ExoMedia version: `3.0.1`
 - Device OS version: `6.0`, '5.1`
 - Devide Manufacturer: `Samsung`, `Motorolla`
 - Device Name: `Galaxy J7`, `Moto E (2nd Gen)`
 
###### Reproduction Steps
1. Initialize EMVideoView in `onCreate()` of the activity or `onPrepared()` of the listener as follows:

`emVideoView = (EMVideoView)findViewById(R.id.custom_video_view);`
`mVideoControls = emVideoView.getVideoControls();`
`mVideoControls.setFastForwardButtonRemoved(false);`
 `mVideoControls.setRewindButtonRemoved(false);`

###### Expected Result
Fast forward and rewind buttons should be visible in the video controller.

###### Actual Result
Fast forward and rewind buttons are not visible in the video controller.

**Comment by brianwernick** [comment]
I guess I need to update some of the documentation (see [setFastForwardImageResource](https://devbrackets.com/dev/libs/docs/exomedia/3.0.0/com/devbrackets/android/exomedia/ui/widget/VideoControls.html#setFastForwardImageResource-int-)); this is working as designed.  The fast forward and rewind buttons don't exist in the `VideoControlsMobile` because the user should be dragging the seek bar instead.

**Comment by devanshuk** [comment]
Thanks for the quick response! Although I wish you could allow to be put in FF and rewind buttons in mobiles as well since the seek bar seeking in accurate intervals like 5 seconds or so. Educational videos or tutorials do warrant for the use of these buttons. Thanks anyway for super useful library!
