### ISSUE TITLE
How can I make contribute a PR here?

### ISSUE THREAD

**Issue by rysh88** [brianwernick/ExoMedia#292]
I noticed that there was no state change listener that I can set for EmVideoView. And I saw ExoPlayerListener but this was not accessible from EmVideoView.
So I want to make a PR to add in this change but I can't make a PR because I get access denied to push my branch to the repo.

**Comment by brianwernick** [comment]
You need to fork the repository and create the branch in your fork.  Then you can create a PR. (This is the standard workflow for GitHub, GitLab, BitBucket, etc.)

**Comment by brianwernick** [comment]
I'm assuming this PR is in reference to #257 ?

**Comment by rysh88** [comment]
I wasn't aware of the issue but it sounds like it's the same need as me. But I'm not sure how old addExoPlayerListener worked but I wanted to add a listener through current ExoPlayerListener.onStateChanged. Since I see that prepare, complete listeners are being called through here as well.
Thanks for the quick response. I will try to fork the repo.

**Comment by brianwernick** [comment]
In the older versions (pre 3.0) the ExoPlayerListener was exposed, I removed this exposure in 3.0 because it had the same issue the MediaPlayer.*Listener's had; they provided implementation details (MediaPlayer versus ExoPlayer).  The solution should be independent on the backend (MediaPlayer or ExoPlayer) so It would need to be a new custom callback with custom states (our own enum really)
