### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by homburg** [brianwernick/ExoMedia#31]
Hi @brianwernick 

Do you have anything planned for Chromecast support?

Seems like it would fit i `EMPlayListService` or as an alternative service with some shared logic.

**Comment by brianwernick** [comment]
I've thought about it a few times and I agree that Chromecast support would be a great fit in `EMPlaylistService`.  However I keep coming up with two reasons that always seem to stop me (or at least delay it);  those being:
1. I want to include Chromecast as an optional dependency which would mean that the `EMPlaylistService` would need to be refactored to support optional (and other) playback destinations.
2. I'm still not sure if I want to use the CastCompanion library, or create my own Chromecast interaction object.

I'll think it through some more over the next few days and get back to you.

**Comment by homburg** [comment]
Looking forward to hearing your thoughts

**Comment by brianwernick** [comment]
OK, so after thinking about this for a few days I have decided against adding Chromecast functionality for a few reasons.

1. This library has already gotten a little out of the original intended scope (as a wrapper around the ExoPlayer) due to the playlist support.
2. There is already a good library focusing on chromecast (CastCompanion).
3. The current setup for the playlists allows you to add Chromecast support by extending the playlist service (as you already have to).

Now as I mentioned you can add Chromecast support in to the playlist service, but it is a little cumbersome so for the next major release I will work on making that easier to do.

**Comment by iamdeadman** [comment]
Hi,

judging from the last activity date here I assume this has already been done ? 
@brianwernick were you able to simplify the chromecast integration and is it already included 
in the exomedia's recent version - 4.3.0 ? If not, can you suggest good alternatives like castcompanion to get chromecasting enabled ?

Also, just one more issue I was facing was I don't know how to extend the playlist items in the playlistservice here. The only methods we are seeing here are setParameters so each time we load more tracks into view should we reset this media items list or is there a way already to extend this media items list in the playlistManager.setParameters(<list<media_item>>, <current_track_id>);

**Comment by brianwernick** [comment]
@iamdeadman ExoMedia hasn't supported the playlist functionality since 3.0 (moved to it's own library [PlaylistCore](https://github.com/brianwernick/PlaylistCore)) which has chromecast support built in to the demo. If you have more questions about chromecast or playlist support please ask it in the PlaylistCore repo instead.
