### ISSUE TITLE
Can't play Android Resource file like VideoView

### ISSUE THREAD

**Issue by danielmaciel** [brianwernick/ExoMedia#32]
When using VideoView you can do this:

Uri video = Uri.parse("android.resource://" + getPackageName() + "/" + R.raw.your_raw_file); //do not add any extension
//if your file is named sherif.mp4 and placed in /raw
//use R.raw.sherif
videoHolder.setVideoURI(video);

This doesn't work on ExoMedia. An exception is thrown:

com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to android.resource://com.njrexperience.android/2131165185

**Comment by brianwernick** [comment]
Hmm, I haven't tested playback from raw resources.  I'll take a look a little later

**Comment by brianwernick** [comment]
Update: I'm still working on this, it's just taking a little bit longer than I originally thought due to the way the URI is handled.

**Comment by brianwernick** [comment]
So I've done some more research in to this and you should be able to use a video from the assets folder (main/assets) with `emVideoView.setVideoURI(Uri.parse("/android_asset/video.mp4"));` assuming your video is named "video.mp4".  There isn't any built in functionality to play videos from res/raw currently, and I don't have plans on adding raw anytime soon since assets works

**Comment by AndroidDeveloperLB** [comment]
Is there a way to use it in the res/raw instead?
