### ISSUE TITLE
Video Player stop unexpectable.

### ISSUE THREAD

**Issue by alexoverseer** [brianwernick/ExoMedia#365]
###### Include the following:
 - ExoMedia version: `3.1.0`
 - Device OS version: all
 - Devide Manufacturer: all
 - Device Name: all
 
###### Reproduction Steps
 1. Initialize player with these URL:
     http://video.jurnaltv.md/gallery_video/10265772.mp4
2. Seek progress to ~ 46:10 minutes

###### Expected Result
Actual video is 59:03 minutes length, it should play to the end.
###### Actual Result
It stops at 46:16 minute, and don't play at all. It can reproduce at any device and any android version. It can reproduce with any video that length is bigger than ~ 40 minutes.

**Comment by brianwernick** [comment]
What is the LogCat output?

**Comment by alexoverseer** [comment]
LogCat is clean, I can't catch any error or something else.

**Comment by brianwernick** [comment]
I tried this over the weekend and was able to play the video (albeit after a long buffer time). Even playing it in a web browser was difficult due to the slow server speed

**Comment by alexoverseer** [comment]
I'm tried with another players (for example: ijkplayer), and he don't stop as your's.

**Comment by brianwernick** [comment]
I tried this on my Nexus 6 (7.0) and saw the same issue, not sure why I wasn't seeing this on my Nexus 4.

The LogCat output is 
>12-28 10:09:54.874 4254-6392/com.devbrackets.android.exomediademo E/AudioTrack: Discontinuity detected [expected 2768289822, got 2768089773]
12-28 10:10:00.171 845-1529/? D/WifiService: acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 uid=10015}
12-28 10:10:00.175 845-1336/? I/WifiHAL: Got channel list with 11 channels
12-28 10:10:00.176 845-1336/? I/WifiHAL: Got channel list with 9 channels
12-28 10:10:00.176 845-1336/? I/WifiHAL: Got channel list with 0 channels
12-28 10:10:00.177 845-1336/? W/WifiHAL: Ignoring invalid attribute type = 37, size = 0
12-28 10:10:00.942 845-3748/? D/WifiService: releaseWifiLockLocked: WifiLock{NlpWifiLock type=2 uid=10015}
12-28 10:10:00.967 18026-3725/? I/GCoreUlr: Successfully inserted 1 locations
12-28 10:10:03.992 402-649/? I/AudioFlinger: BUFFER TIMEOUT: remove(4101) from active list on thread 0xafc94b40

I then tried this with the 1.5.13 ExoPlayer demo with the same results, however it appears to be fixed in the ExoPlayer 2.0 release. As such this is part of #311
