### ISSUE TITLE
Puedo trasmitir exomedia a chromecast

### ISSUE THREAD

**Issue by Danytech-Academic** [brianwernick/ExoMedia#372]
Pregunta puedo trasmitir un vídeo reproducido con la librería de exomedia a el chromecast
> can I transmit a video played with the exomedia library to the chromecast

**Comment by brianwernick** [comment]
Please use English in the future.

Google Cast devices (including the Chromecast) work by playing media specified via a URL (or a custom receiver can work differently). Because of this the media player on the mobile device (sender) doesn't matter.

If your question was about displaying progress and control playback then: It is possible, however will take some work to re-route the button (and progress) functionality to handle both remote and local files. For an example you can see https://github.com/brianwernick/ExoMedia/blob/master/demo/src/main/java/com/devbrackets/android/exomediademo/manager/PlaylistManager.java#L62
