### ISSUE TITLE
[Question] Remote file .ts with no seek and no duration, is it ok?

### ISSUE THREAD

**Issue by Kyba1985** [brianwernick/ExoMedia#381]
Context:

 - ExoMedia version: `3.1.1`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `p9 lite`
 
I have problems with duration and seek on remote file from google drive. The seek doesn't work and the duration is not shown. If i play another video mp4 the seek and duration works. There are same limitations on this type of file?

**Comment by brianwernick** [comment]
`.ts` files are generally used as a part of a larger stream (e.g. HLS, H.264) and may not contain all the information necessary for the seek bar. In this case it sounds like there is no duration in the Metadata which is why seeking isn't available.

If I remember correctly, one of the main enhancements in ExoPlayer 2.0 is increased support for seeking in video streams. Though I believe that is only in reference to live streams (i.e. realtime), the added support may include determining durations when none is specified.
