### ISSUE TITLE
Does any one in this group implement Exo player with Expressplay to play PDCF content

### ISSUE THREAD

**Issue by satyamub** [brianwernick/ExoMedia#383]
Hi All,

I am trying to run a PDCF content (.mlv) file which is generated from expressplay dashboard. We are using the test sdk of the expressplay. We are using Media Source Type as "SINGLE _FILE". Still we can not able to play. It seems like, its creating a m3u8 playlist from the mlv but not able to play.

When we use the VideoView, it shows, that the m3u8 file is not found error.

Can you people help?

**Comment by brianwernick** [comment]
Is the url you are passing to the VideoView of the extension `.m3u8` or is it `.mlv`? If it is the latter than the issue is that `.mlv` is not a recognized format so the default `RenderBuilder` is used instead of the `HlsRenderBuilder`. There are a few ways that you can add the support in your app
 1. Provide a custom `RenderBuilder` that handles `.mlv`
 2. Extract the `.m3u8` url and pass that in

**Comment by satyamub** [comment]
@brianwernick   when we provide mp4 to bento4 tool for expressplay DRM protection, this returns .mlv file. I now succeed to play.

**Comment by brianwernick** [comment]
So playing `.mlv` files is now working? If so what did you do to add it (for anyone else that has the same question)
