### ISSUE TITLE
Question: Display last frame when video completes

### ISSUE THREAD

**Issue by martijnvm** [brianwernick/ExoMedia#413]
The widget VideoView from the Android SDK, shows the last frame of the video upon completion. I wonder if this also feasible with the EMVideoView. 

This is my piece of code:
```java
videoView = new EMVideoView(getContext().getApplicationContext());
videoView.setPreviewImage(previewBitmap);
videoView.setVideoURI(getVideoUrl());
videoView.setOnPreparedListener(this :: startVideo);
addView(videoView, 0);
```

startVideo just calls `.start()` on the `videoView`.

When the video completes, the EMVideoView is just blank.

**Comment by brianwernick** [comment]
I seem to remember that early on the EMVideoView did show the last frame until the surface was destroyed (e.g. leaving the activity) or a new video was requested. I'm fairly certain that it was removed due to an issue (which may no longer exist) so I'll update this to a feature request (vs the question).

As to answering the question part:
There is no built in functionality for this, nor will It be easy to add because of the multiple layers that handle clearing the surface in states. What happens is when the `EMVideoView` receives a completion state it tells the playback to stop which will update the internal state, abandon audio focus, etc. In the process of clearing out the state the `EMExoPlayer` will also clear the surface of the VideoView. So in order to add the functionality you will need to extend multiple classes (`EMVideoView`, `ExoVideoView`, and the `EMExoPlayer`) (or fork the repo, make the changes, and use your own build).  That being said, I'm pretty close to a `4.0` release so I'll see if I can get this in before then

**Comment by martijnvm** [comment]
I reverted back to 2.x.x until the current API started to break. No luck their either unfortunately. I'll just wait for 4.0.0 and hope you would be able to fix it :).

Thanks for the support!
