### ISSUE TITLE
Using Exoplayer extensions..

### ISSUE THREAD

**Issue by AdityaAnand1** [brianwernick/ExoMedia#471]
Would it be possible to add support for [Exoplayer extensions](https://github.com/google/ExoPlayer/tree/release-v2/extensions) for playing opus and flac files in ExoMedia?

**Comment by brianwernick** [comment]
This is already supported with [`ExoMedia.registerRenderer()`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L48), [`ExoMedia.registerMediaSourceBuilder()`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L59), and [`ExoMedia.setHttpDataSourceFactoryProvider()`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L71)

**Comment by httpdispatch** [comment]
@brianwernick how to use opus extension with exomedia? If i just include ExoPlayer locally i have the compilation error
`"com.android.tools.r8.errors.CompilationError: Program type already present: com.google.android.exoplayer2.C$AudioContentType"`

Should i also include exomedia locally and override dependencies to use local instance of ExoPlayer?

**Comment by httpdispatch** [comment]
@brianwernick ok, i've managed to run opus extension. I had to update opus build.gradle and change `implementation` to `provided`
```
provided project(modulePrefix + 'library-core')
```

But `ExoMedia` still can't use the plugin because of missing required constructor. ExoMedia searches for the `Constructor(Handler.class, AudioRendererEventListener.class)` in the `RendererProvider`

```
Constructor<?> constructor = clazz.getConstructor(Handler.class, AudioRendererEventListener.class);
```
But `LibopusAudioRenderer` doesn't contain such constructor so the lookup throws an exception which is, btw, suppressed by the `ExoMedia`

So i also had to add a constructor to the `LibopusAudioRenderer`
```
public LibopusAudioRenderer(Handler eventHandler, AudioRendererEventListener eventListener) {
    this(eventHandler, eventListener, new AudioProcessor[]{});
}
```
Now that works.
