### ISSUE TITLE
Video Caching Support

### ISSUE THREAD

**Issue by saefbadwan** [brianwernick/ExoMedia#487]
dose it support video cashing ,, i mean when you load a url dose it chash it ?

**Comment by brianwernick** [comment]
See #328 for an older answer, however there is a different way to do this in `4.0.0`+

This is still a little bit wonky because I used too restrictive of a return type (this might become less restrictive in 4.1 if it isn't breaking) in  [ExoMedia#setHttpDataSourceFactoryProvider()](https://github.com/brianwernick/ExoMedia/blob/4.0.0/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L71) so instead you will need to override a `MediaSourceProvider` with [ExoMedia#registerMediaSourceBuilder()](https://github.com/brianwernick/ExoMedia/blob/4.0.0/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L59) that handles the caching via the ExoPlayers [CacheDataSourceFactory](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/upstream/cache/CacheDataSourceFactory.html). 

An example of this for HLS would be
```java
    protected static class CachedHlsMediaSourceBuilder extends HlsMediaSourceBuilder {
        public static final int CACHE_SIZE_BYTES = 50 * 1024 * 1024;

        @NonNull
        protected DataSource.Factory buildDataSourceFactory(@NonNull Context context, @NonNull String userAgent, @Nullable TransferListener<? super DataSource> listener) {
            ExoMedia.HttpDataSourceFactoryProvider provider = ExoMedia.Data.httpDataSourceFactoryProvider;
            HttpDataSource.BaseFactory httpDataSourceProvider = provider != null ? provider.provide(userAgent, listener) : new DefaultHttpDataSourceFactory(userAgent, listener);

            Cache cache = new SimpleCache(context.getCacheDir(), new LeastRecentlyUsedCacheEvictor(CACHE_SIZE_BYTES));
            return new CacheDataSourceFactory(cache, httpDataSourceProvider, CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR | CacheDataSource.FLAG_IGNORE_CACHE_FOR_UNSET_LENGTH_REQUESTS);
        }
    }
```

Then register it with
```java
        ExoMedia.registerMediaSourceBuilder(new MediaSourceProvider.SourceTypeBuilder(new CachedHlsMediaSourceBuilder(), ".m3u8", ".*m3u8.*"));
```

**NOTE:** The `MediaSourceBuilder` passed to `registerMediaSourceBuilder()` will take precedence over existing builders which is why registering a new HLS (or SmoothStream, Dash, etc.) works

**Comment by androidovshchik** [comment]
It's here @brianwernick 
https://github.com/brianwernick/ExoMedia/blob/master/demo/src/main/kotlin/com/devbrackets/android/exomediademo/App.kt
