### ISSUE TITLE
get scaled bitmap from ExoTextureVideoView

### ISSUE THREAD

**Issue by TrungVuHD** [brianwernick/ExoMedia#489]
I am using ExoTextureVideo#getBitmap function to get the Bitmap of the current frame.
I can get the bitmap, but I have a problem with the portrait video. The video is displayed in portrait mode (width < height) of a landscape VideoView(width > height), but when I try to get the bitmap, it returns a landscape bitmap rather than a portrait bitmap.

Can you tell me how to get the portrait bitmap in my situation?

**Comment by brianwernick** [comment]
The backing view (TextureView) will return a bitmap that matches the current on-screen representation. Because the `VideoView` is a wrapper for the `TextureView` (or `SurfaceView`) implementation along with the video controls it will, by default, wrap the size of the video which is why the image you are getting doesn't have black bars on the top/bottom of the video

**Comment by TrungVuHD** [comment]
So do you have any suggestion for that situation?
for what I've done so far, I used canvas to draw a bitmap with some calculated offset value. It's ok with landscape video. But it's wrong width portrait video.
Or do we have any way to detect a video is portrait or landscape?

**Comment by brianwernick** [comment]
I don't know what the question is now; I told you that the image you get will essentially be that of the video regardless of the current orientation. This doesn't sound like a library specific question now so I'm going to close this as stackoverflow or a similar site is more appropriate
