### ISSUE TITLE
Get underlined SimpleExoPlayer 

### ISSUE THREAD

**Issue by nativ18** [brianwernick/ExoMedia#537]
How could I get the internal used SimpleExoPlayer out of the VideoView.
The use case is to toggle between fullscreen video and video cell in a RecycleView while maintaining the position and the buffering.

**Comment by brianwernick** [comment]
Because of the layers of abstraction used to handle the swapping between ExoPlayer & MediaPlayer backings and the SurfaceView & TextureView implementations of those backings it's not simple however it can be done by extending a few classes.
The classes in question are:
  * [ExoVideoDelegate](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoVideoDelegate.java) which holds a `protected` `ExoMediaPlayer` that is the base ExoPlayer backing
  * [ExoSurfaceVideoView](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoSurfaceVideoView.java) or [ExoTextureVideoView](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoTextureVideoView.java) which is the ExoPlayer backed versions and holds a `protected` `ExoVideoDelegate`
  * [VideoView](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java) which holds the implementations that we need to extend

I'm going to work my way from the bottom to the top dependency wise so I'll start with the `ExoVideoDelegate`. Because you'll be sharing a `ExoMediaPlayer` between views you will need to override [ExoVideoDelegate#initExoPlayer()](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoVideoDelegate.java#L211) to use the provided one instead of creating a new one (Note: you'll still need to set the listeners as that method does).

Once that is setup you will need to override [ExoTextureVideoView#setup()](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoTextureVideoView.java#L176) or [ExoSurfaceVideoView#setup()](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoSurfaceVideoView.java#L175) to set the `delegate` to your new customized one instead of the default `ExoVideoDelegate`.

Now extending the `VideoView` isn't necessary depending on how you choose to handle setting the `ExoMediaPlayer` and how you specify the `VideoViewApi` implementation. If you don't want to extend the `VideoView` you can specify the `videoViewApiImpl` in the xml layout (see an [example](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/res/layout/exomedia_default_exo_surface_video_view.xml))

**Comment by nativ18** [comment]
Thank you for the reply. 
It seems to be a complex implementation in order to achieve what I need.

What I'm trying to do is to play the video in fullscreen if the user clicks it from a RecyleView. I don't want the **position** and the **buffering** to be missed. With the ExoPlayer and MediaPlayer you can simply do it by setting the new SurfaceView/TextureView into the current player. 

This is why I asked you how I can get the player in ExoMedia. If you see a simplest solution to achieve my goals please let me know
