### ISSUE TITLE
Any plans for supporting exoplayer's dev-v2?

### ISSUE THREAD

**Issue by AdityaAnand1** [brianwernick/ExoMedia#549]
The developers of exoplayer [are working](https://github.com/google/ExoPlayer/issues/3651) on a critical new improvement, faster seeking, in the dev v2 branch.

I was wondering perhaps if we could have a mirrored branch of exoMedia as well to adopt the new changes?

**Comment by brianwernick** [comment]
While I understand that there are times where we want some of the in-progress features from ExoPlayer, the overhead work from issues, maintenance, etc. that would be caused by having a branch that depends on the dev branch of ExoPlayer to build is more than I'm willing to take on. If you really want the changes in dev-v2 before they perform a release you have a few choices;
  1. Use something like JitPack to override the version of ExoPlayer that ExoMedia uses
  2. Fork ExoMedia and make the changes in a repo for your own use (and use either a submodule or JitPack)
