### ISSUE TITLE
Leak Warning in ExoMedia-Demo

### ISSUE THREAD

**Issue by quiKsilverItaly** [brianwernick/ExoMedia#582]
Hey, thank you for this great project. 

I wanted to ask, if the warning about a possible Memory Leak in your demo project (see Screenshot: https://www2.pic-upload.de/img/35041004/leak.png) is relevant? If there is really a risk, how can I fix it?

**Comment by brianwernick** [comment]
Normally I would use a dependency injection framework such as Dagger (2) however for the demo app I wanted to keep it as simple as possible. In a production application this is definitely a concern and should be stored in a non-static field in the Application class if you aren't using an injection framework. I should probably update the demo to reflect this because I'm also using the `onTerminate()` method which is only called for emulators.

What you would need to do would be something like 
```java
public class App extends Application {
    @Nullable
    private PlaylistManager playlistManager;

    @Nullable
    public PlaylistManager getPlaylistManager() {
        return playlistManager;
    }
}
```

where the use would be  `((App) context.getApplicationContext()).getPlaylistManager()` making sure to pay attention to nulls

**Comment by quiKsilverItaly** [comment]
Thank you for this great answer!

I implemented getPlaylistManager like that, to avoid nulls:

```
    public PlaylistManager getPlaylistManager() {

        if(playlistManager == null) {

            new PlaylistManager(this);
        }

        return playlistManager;
    }

```
