### ISSUE TITLE
Can add an example of playing RTSP and RTMP video?

### ISSUE THREAD

**Issue by zhengoogle** [brianwernick/ExoMedia#585]
The current version of Exoplayer already supports RTSP video. Can add an example of playing RTSP/RTMP video?

**Comment by brianwernick** [comment]
Currently the ExoPlayer does *Not* support RTSP but it is being worked on (see https://github.com/google/ExoPlayer/issues/55). For RTMP see #566

**Comment by zhengoogle** [comment]
Exoplayer already supports RTSP video，[Add RTSP support #3854](https://github.com/google/ExoPlayer/pull/3854)

**Comment by brianwernick** [comment]
That PR hasn't been merged and is still in need of a lot of work before they are ready for it to be merged. As such ExoPlayer (released) still doesn't support RTSP. If you want to play with rtsp you'll have to 
1. download the ExoPlayer source
2. follow their guide for including it as a module
3. download the ExoMedia source and use ExoPlayer as a module instead of an artifact
4. Include an RTSP builder
5. build ExoMedia in to an aar
6. use that aar in your app.

I've done this on my machine but because there is so much pending work on that branch I won't post how it was done because it will change soon

**Comment by zhengoogle** [comment]
thanks for your help
