### ISSUE TITLE
Setting the volume and playback speed

### ISSUE THREAD

**Issue by codinronan** [brianwernick/ExoMedia#593]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.1.0`
 
Hi there,

First - amazing library! I've been struggling with something much, much older and it is so brittle I just can't take it any further, so I decided to go for something more powerful and up to date. 

I do have a quick question: I am working on creating a custom player and I want to be able to set volume and the playback rate. I have followed the chain of objects (there's not much documentation..) and realized that although the AudioPlayer itself supports setting these things, there's simply no way to invoke them via the means the demo uses (AudioPlayerActivity -> playlistManager -> sends intent to MediaService -> PlaylistHandler -> MediaPlayerApi object which wraps the AudioPlayer)

That chain works fine for anything supported by the BasePlaylistService, but alas it does not support everything that the AudioPlayer itself does. How would you best recommend setting these values directly on my AudioApi object (similar to what you have in the demo) without breaking the layers of abstraction you've created?

I guess I could directly extract and cast the player api, and then set the values? Something like:

```
        MediaItem item = null; //e.g. one not actually null
        List<MediaPlayerApi<MediaItem>> players = playlistManager.getMediaPlayers();
        MediaPlayerApi<MediaItem> player = null;
        for(MediaPlayerApi<MediaItem> o : players) {
            if(o != null && o.handlesItem(item)) {
                player = o;
            }
        }
        if (player != null) {
            ((AudioApi)player).setVolume(0.4, 0.6); // or whatever. seek, set playback rate, etc
        }
```

Does this seem appropriate? How would you do it, if you are controlling this e.g. from AudioPlayerActivity in the demo?

Edit: Oh I guess one other thing, to actually support the volume I think a new version needs to be published to jcenter right, since you just added them.

Thank you :)

**Comment by brianwernick** [comment]
Part of this question relates to how the library used in the demo app for playlists ([PlaylistCore](https://github.com/brianwernick/PlaylistCore)) however I'll answer it here because there's other parts that touch `ExoMedia` as well.

In order to _get_ the current volume you are correct, you will need to wait for the next release however you can currently _set_ the volume and store that value if you want to in the meantime. As far as the abstraction goes and calling methods from your own `MediaPlayerApi` implementation you are on the right track with casting it. I would personally make sure that it can be cast before actually casting it though. e.g.
```java
if (player != null && player instanceof AudioApi) {
    ((AudioApi) player).setVolume(0.4f, 0.6f);
}
```

It might be worth adding an additional layer if you want to be able to get/set values for both the `AudioApi` and `VideoApi` (or whatever you end up calling them)
