### ISSUE TITLE
What should be done if I want to use it inside live wallpaper?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [brianwernick/ExoMedia#628]
After all, it doesn't have views...
I want to put it and view it in various scaling methods, but for now I've found out only how to do it with the normal MediaPlayer, and it scales it by stretching, which isn't nice:
https://stackoverflow.com/q/50091878/878126

**Comment by brianwernick** [comment]
As it's currently architected you would have to use the `ExoMediaPlayer` directly which bypasses the point of ExoMedia instead of just using ExoPlayer directly. This is something I've been thinking about updating in the architecture for 5.0 however there's no guarantee that it would work or that I will change in that direction. As such I would recommend using ExoPlayer directly instead of ExoMedia for this case.

**Comment by AndroidDeveloperLB** [comment]
ok thanks
