### ISSUE TITLE
Problem with a stream

### ISSUE THREAD

**Issue by mmguerras** [brianwernick/ExoMedia#686]
Hello,

We have encountered a problem using the player. While 99.9% of the streams work perfect, this one doesn’t have sound: http://radiomarca.streaming-pro.com:8030/radiomarca.mp3

The player connects to the radio stream but it doesn’t sound. If we open it on any web browser in the same test phone, the stream works fine. Any other mp3 (even from the same server) works fine, like this one http://rmc-eibar1.streaming-pro.com:7000/link_rmarca.mp3

We have over 500 streams and this is the only one we’ve faced this issue. We’ve tried using 4.2.3 and 4.3.0, even making an independent project just with the player gave us the same result.

Any help is appreciated.

Thanks.

**Comment by brianwernick** [comment]
My assumption is that it's using a format not supported by ExoPlayer. Please post the logcat related to the playback of the failing stream

**Comment by mmguerras** [comment]
Logcat:

> E/ExoPlayerImplInternal: Source error.

onError exception:

> com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://radiomarca.streaming-pro.com:8030/radiomarca.mp3

**Comment by brianwernick** [comment]
What do you expect to happen when the stream can't connect?
> Unable to connect to http://radiomarca.streaming-pro.com:8030/radiomarca.mp3

**Comment by mmguerras** [comment]
This stream is working but throws that exception after a few seconds.

**Comment by brianwernick** [comment]
This looks like a live stream which is most likely causing the issue due to the ExoPlayer thinking the end of stream has been reached (I haven't verified this). If this is the case you'll need to override the duration with [overrideDuration](https://github.com/brianwernick/ExoMedia/blob/80985d70ec7a359d54b04ddc48d30dd1dd341e0a/library/src/main/java/com/devbrackets/android/exomedia/AudioPlayer.java#L307) otherwise the [MuxNotifier.shouldNotifyCompletion](https://github.com/brianwernick/ExoMedia/blob/80985d70ec7a359d54b04ddc48d30dd1dd341e0a/library/src/main/java/com/devbrackets/android/exomedia/AudioPlayer.java#L469) will get called early (the other option is to extend the AudioPlayer and override the completion criteria
