### ISSUE TITLE
Display next and previous buttons after error

### ISSUE THREAD

**Issue by spurgeon** [brianwernick/ExoMedia#696]
[X] I have verified there are no duplicate active or recent bugs, questions, or requests

Is there a way to display the controls after an error occurs when loading a video file?  I would like to have the next and previous buttons still visible, allowing users to skip to the previous or next video, but all I see is the indeterminate progress view.

For example, set the controls to visible:

    VideoControls controls = mVideoView.getVideoControls();
    controls.setNextButtonRemoved(false);
    controls.setNextButtonEnabled(currentIndex < mRelatedFiles.size() - 1); // not at end
    controls.setPreviousButtonRemoved(false);
    controls.setPreviousButtonEnabled(currentIndex > 0); // not at beginning

Handle the error condition:

    mVideoView.setOnErrorListener(new OnErrorListener() {
        @Override
        public boolean onError(Exception e) {
            // TODO Do something here to display the next and previous buttons
            return false;
        }
    });

I've tried to explicitly show the controls with the following, but no luck: `controls.showLoading()`, `controls.show()`, `mVideoView.showControls()`.

I can, of course, hide the VideoView and then show my own view with an error message and previous and next buttons, but this seems like a waste when the buttons might be available with the VideoView controls already.

**Comment by brianwernick** [comment]
Because the controls state is still "loading" it will filter out any controls showing events [here](https://github.com/brianwernick/ExoMedia/blob/759adcf670882a057df1236850d406a1f783f08a/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsMobile.java#L163). You'll need to call [finishLoading](https://github.com/brianwernick/ExoMedia/blob/759adcf670882a057df1236850d406a1f783f08a/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsMobile.java#L208) and hide any of the controls you don't want to see (e.g. play/pause button)

**Comment by spurgeon** [comment]
Thank you, this works, but I don't see a hook for the visibility of the SeekBar, current time text, and duration text.  Are there hooks for those?  (Also, thank you very much for creating this helpful project).

**Comment by brianwernick** [comment]
Unfortunately those views are protected so you will need to extend the `VideoControlsMobile` (and `VideoControlsLeanback` if you have a TV app) to get access to those (`VideoControls` can be specified with [setControls](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java#L238))

**Comment by spurgeon** [comment]
Thanks, will look into that.
