### ISSUE TITLE
video .flv is work ?

### ISSUE THREAD

**Issue by diaconuliviu85** [brianwernick/ExoMedia#72]
Hello

I want to thank you for your hard work.

I fail to make it work .flv, or not supported by exoplayer?

**Comment by brianwernick** [comment]
FLV is partially supported.  This is due to the implementation that was done in the [ExoPlayer][ExoPlayer] which doesn't support all Audio and Video formats.  Additionally .flv playback doesn't support seeking, so I would avoid using any .flv media (at least until all formats are supported).

[ExoPlayer]:https://github.com/google/ExoPlayer/tree/master/library/src/main/java/com/google/android/exoplayer/extractor/flv

**Comment by diaconuliviu85** [comment]
I understand.
then we should expect a new update exoplayer.
Thank you very much.
