### ISSUE TITLE
Many requests to server

### ISSUE THREAD

**Issue by GlebMikhailov** [brianwernick/ExoMedia#798]
### Environment:
 - ExoMedia version: `5.0.0`
 
### Problem:
1. There is a master playlist, for example, https://domainname/record-tm/playlist.m3u8 , inside it are links by bitrates. The player receives these links by bitrates.
2.  Bitrate links contain the session identifier hlssid and look like this https://domainname/record-tm/playlist.m3u8?somedata... a inside these links is a list of .ts files (chunks)
3. The player takes the master playlist from point 1 and creates a new session with a new hlssid
4. From the playlist with chunks (which is attached to the session) from point 2, presumably downloads one .ts file.
5. After that, he again takes the master playlist, creates a new session with a new hlssid and repeats the whole procedure.

But I don't need the last step. How can I set the minimum time to update requests or cancel these requests?

This happens when I call `setMedia` in my code.

**Comment by brianwernick** [comment]
In you case do the HLS manifests represent a Live or Streaming situation where media is being added to the end? I'm seeing a similar situation with the sample app and the Live Stream HLS, but the On-Demand HLS only requests the manifest once as expected. 

For Live/Streaming HLS this is somewhat expected because we need to refresh the manifest periodically (based on segment length & delays) to find new segments.
