### ISSUE TITLE
EMVideoView Add WakeLock support

### ISSUE THREAD

**Issue by johywang** [brianwernick/ExoMedia#84]
First off, want to say that this is a fantastic library!

During video playback, the EMVideoView is not keeping the device awake. Looking at the source, it appears that the start() function calls EMExoPlayer.setPlayWhenReady(), which calls stayAwake(). However, wakeLock in EMExoPlayer is null, so stayAwake() does nothing.

Not sure if that's a bug or is intended, but it would be nice if that can be fixed or have the EMExoPlayer.setWakeMode function be exposed in EMVideoView.

**Comment by brianwernick** [comment]
This is currently working as designed because the Android VideoView provides no direct way to specify the wake mode.  You can however specify the Android VideoView wake mode with on of the callbacks/listeners that returns the MediaPlayer.  Since I will be creating a wrapper around these objects for listeners in 3.0.0, you will be able to specify the wake mode for both root implementation classes (VideoView and ExoPlayer)

**Comment by johywang** [comment]
Gotcha, I see the intent now. For the time being, I'll set the wake mode per your suggestion. Thanks.

**Comment by brianwernick** [comment]
Keeping the screen on has been re-added in https://github.com/brianwernick/ExoMedia/commit/2953ee1c017f4b429fb39713c10af6acd4d07795
