### ISSUE TITLE
Hear sound but not display video in lower API devices

### ISSUE THREAD

**Issue by AmirHadifar** [brianwernick/ExoMedia#93]
Hi Again :D 
I have this issue in some 4.0.* devices And according to this [solution](http://stackoverflow.com/questions/2184364/android-video-hear-sound-but-no-video) try to fix that But I couldn't find any SurfaceView. 

Do you know what's the problem ?

**Comment by brianwernick** [comment]
The SO question you linked isn't using the Android VideoView, they are performing their own setup with a SurfaceView and the MediaPlayer.

**Comment by afollestad** [comment]
This problem also occurs on ARC Welder if you force the use of MediaPlayer instead of ExoPlayer.

**Comment by brianwernick** [comment]
@AmirHadifar 
Because I don't have a device that I've ever seen this issue on would you mind helping me by testing this with on the [3.0 branch](https://github.com/brianwernick/ExoMedia/tree/3.0)? 

If it doesn't work, and you have some time, I would greatly appreciate you testing the linked solution (or others you may have come across in the meantime).

**Comment by AmirHadifar** [comment]
@brianwernick Sure I try to fix it ;)

**Comment by AmirHadifar** [comment]
Hi , first Thanks for your effort on this library 
I tested on Samsung GT-P3100 , Android 4.0.4 :

- [x] 3GP
- [x] HLS
- [x] MKV
- [x] MP4
- [x] MPEG DASH
- [ ] Smooth Stream ( camindes:Llama ... ) 
- [x] Smooth Stream ( Tears of Steel .. ) 
- [x] WEBM

except **Smooth Stream( camindes:Llama )** all them work fine in your new version.

I also checked 2.5.6 version of yourr library
**MPEG Dash** (both of them)  , **Smooth Stream(camindes:Llama)** not worked.

**Comment by brianwernick** [comment]
I'm actually surprised that `MPEG DASH` and `Smooth Stream` (Tears...) worked at all because the 4.0.x platform doesn't normally support them.  As such it sounds like videos are displaying correctly now and I'll close the issue.

@afollestad I'm going to use #94 as an "Add ARC Welder Support" bug and fix the video issue there
